### ISSUE TITLE
NSIS usage example

### ISSUE THREAD

**Issue by itayo** [awaescher/PathEd#1]
Hi.
According to your post (atleast i think it is you) on 
[stack**overflow**](https://stackoverflow.com/a/52864369) you recommend this to be used for safe enviromental updates with NSIS.

However i cannot get this to work.
Do you have any usage example how to use it?

i tried with the following without any lock
install path is "c:\demo path"
'''
File "PathEd.exe"
ExecWait "c:\demo path\PathEx.exe add $\"c:\demo path$\""
'''
Br
Stefan

**Comment by awaescher** [comment]
Hi Stefan,

good point. I use PathEd in my tool [RepoZ](https://github.com/awaescher/RepoZ).
The NSIS script over there shows how PathEd can be used to [add a path](https://github.com/awaescher/RepoZ/blob/496d4f7539670112772b81e208c2ce650164e101/_setup/RepoZ.nsi#L59) and how it can be [removed during uninstallation](https://github.com/awaescher/RepoZ/blob/496d4f7539670112772b81e208c2ce650164e101/_setup/RepoZ.nsi#L92).
