### ISSUE TITLE
Include a licence

### ISSUE THREAD

**Issue by nilp0inter** [awaescher/PathEd#3]
Hi,

I'd like to use PathEd in my own NSIS installer, but without any explicit licence I just can't do it.

I suggest you include a permissive licence text in your repo e.g: Apache, to allow other people redistribute your executable as part of their installers.

Thank you for the tool!

**Comment by awaescher** [comment]
Hi, thanks for the hint and being fair to OSS.
I just added the MIT license, hope that'll suit you well.

**Comment by nilp0inter** [comment]
Perfect, thank you!
