### ISSUE TITLE
Is PathEd still maintained?

### ISSUE THREAD

**Issue by anf** [awaescher/PathEd#5]
Hello there,
It seems like PathEd is not actively maintained and the last commit was *ages* ago. If you want/can, you should add a note to use a tool more actively maintained and feature-rich for Windows. And yes, it's a repository maintained by me!

Please see [github.com/ANF-Studios/WinPath](https://github.com/ANF-Studios/WinPath). It's actively under development and a lot is planned.

**Comment by awaescher** [comment]
I am still here, yes. PathEd however does everything I need it to have so there's no issue in not having commits.

**Comment by anf** [comment]
Oh, I see, thanks.
